services:
  - type: web
    name: fcloset
    env: ruby
    plan: free
    buildCommand: "bundle install && rails assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Fcloset_db
          property: connectionString
    migrationsCommand: "bundle exec rails db:migrate"
