services:
  - type: web
    name: fcloset
    env: ruby
    plan: free
    buildCommand: "bundle install && rails assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Fcloset_db
          property: connectionString

  - type: web
    name: fcloset-migrations
    env: ruby
    plan: free
    buildCommand: "bundle install"
    startCommand: "bundle exec rails db:migrate"
    autoDeploy: false # ←これで勝手に動かないようにできる（任意）
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Fcloset_db
          property: connectionString

databases:
  - name: Fcloset_db
